services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study
      POSTGRES_DB: posts_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U study -d posts_db"]
      interval: 2s
      timeout: 3s
      retries: 15
volumes:
  postgres_data:

