# TODO: python:3.12-slim 기반 이미지를 지정하세요.
# TODO: 작업 디렉터리를 /app으로 지정하세요.
# TODO: requirements.txt를 먼저 복사하고 pip 의존성을 설치하세요.
# TODO: app 디렉터리를 /app/app으로 복사하세요.
# TODO: 일반 사용자를 생성하고 해당 사용자로 전환하세요.
# TODO: 8000 포트를 문서화하세요.
# TODO: exec 형식 CMD로 uvicorn을 실행하세요.
